# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# Calculator Through python program/


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(410, 609)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.acBtn = QtWidgets.QPushButton(self.centralwidget)
        self.acBtn.setGeometry(QtCore.QRect(10, 90, 191, 91))
        self.acBtn.setStyleSheet("QPushButton{\n"
        "font: 75 26pt \"MS Shell Dlg 2\";\n"
        "color: rgb(255, 255, 255);\n"
        "background-color: rgb(0,0,0);\n"
        "border:2px solid;\n"
        "border-color: rgb(255, 0, 0);\n"
        "border-radius:20px;\n"
        "}\n"
        "QPushButton:hover{\n"
        "    color: rgb(0, 0, 0);\n"
        "    background-color: rgb(255, 0, 0);\n"
        "}\n"
        "")
        self.acBtn.setObjectName("acBtn")
        self.nineBtn = QtWidgets.QPushButton(self.centralwidget)
        self.nineBtn.setGeometry(QtCore.QRect(210, 190, 91, 91))
        self.nineBtn.setStyleSheet("QPushButton{\n"
        "font: 75 26pt \"MS Shell Dlg 2\";\n"
        "color: rgb(255, 255, 255);\n"
        "border:2px solid;\n"
        "border-color: rgb(0, 255, 0);\n"
        "background-color: rgb(0,0,0);\n"
        "border-radius:20px;\n"
        "}\n"
        "QPushButton:hover{\n"
        "    color: rgb(0, 0, 0);\n"
        "    \n"
        "    background-color: rgb(0, 255, 0);\n"
        "}\n"
        "")
        self.nineBtn.setObjectName("nineBtn")
        self.eightBtn = QtWidgets.QPushButton(self.centralwidget)
        self.eightBtn.setGeometry(QtCore.QRect(110, 190, 91, 91))
        self.eightBtn.setStyleSheet("QPushButton{\n"
        "font: 75 26pt \"MS Shell Dlg 2\";\n"
        "color: rgb(255, 255, 255);\n"
        "background-color: rgb(0,0,0);\n"
        "border:2px solid;\n"
        "border-color: rgb(0, 255, 0);\n"
        "border-radius:20px;\n"
        "}\n"
        "QPushButton:hover{\n"
        "    color: rgb(0, 0, 0);\n"
        "    \n"
        "    background-color: rgb(0, 255, 0);\n"
        "}\n"
        "\n"
        "")
        self.eightBtn.setObjectName("eightBtn")
        self.sevenBtn = QtWidgets.QPushButton(self.centralwidget)
        self.sevenBtn.setGeometry(QtCore.QRect(10, 190, 91, 91))
        self.sevenBtn.setStyleSheet("QPushButton{\n"
        "font: 75 26pt \"MS Shell Dlg 2\";\n"
        "color: rgb(255, 255, 255);\n"
        "background-color: rgb(0,0,0);\n"
        "border:2px solid;\n"
        "border-color: rgb(0, 255, 0);\n"
        "border-radius:20px;\n"
        "}\n"
        "QPushButton:hover{\n"
        "    color: rgb(0, 0, 0);\n"
        "    \n"
        "    background-color: rgb(0, 255, 0);\n"
        "}\n"
        "")
        self.sevenBtn.setObjectName("sevenBtn")
        self.delBtn = QtWidgets.QPushButton(self.centralwidget)
        self.delBtn.setGeometry(QtCore.QRect(210, 90, 91, 91))
        self.delBtn.setStyleSheet("QPushButton{\n"
        "font: 75 20pt \"MS Shell Dlg 2\";\n"
        "color: rgb(255, 255, 255);\n"
        "background-color: rgb(0,0,0);\n"
        "border:2px solid;\n"
        "border-color: rgb(213, 213, 213);\n"
        "border-radius:20px;\n"
        "}\n"
        "QPushButton:hover{\n"
        "    color: rgb(0, 0, 0);\n"
        "    \n"
        "    background-color: rgb(213, 213, 213);\n"
        "}\n"
        "")
        self.delBtn.setObjectName("delBtn")
        self.divBtn = QtWidgets.QPushButton(self.centralwidget)
        self.divBtn.setGeometry(QtCore.QRect(310, 90, 91, 91))
        self.divBtn.setStyleSheet("QPushButton{\n"
        "font: 75 26pt \"MS Shell Dlg 2\";\n"
        "color: rgb(255, 255, 255);\n"
        "background-color: rgb(0,0,0);\n"
        "border:2px solid;\n"
        "border-color: rgb(255, 255, 0);\n"
        "border-radius:20px;\n"
        "}\n"
        "QPushButton:hover{\n"
        "    color: rgb(0, 0, 0);\n"
        "    background-color: rgb(255, 255, 0);\n"
        "}\n"
        "")
        self.divBtn.setObjectName("divBtn")
        self.multiBtn = QtWidgets.QPushButton(self.centralwidget)
        self.multiBtn.setGeometry(QtCore.QRect(310, 190, 91, 91))
        self.multiBtn.setStyleSheet("QPushButton{\n"
        "font: 75 26pt \"MS Shell Dlg 2\";\n"
        "color: rgb(255, 255, 255);\n"
        "background-color: rgb(0,0,0);\n"
        "border:2px solid;\n"
        "border-color: rgb(255, 255, 0);\n"
        "border-radius:20px;\n"
        "}\n"
        "QPushButton:hover{\n"
        "    color: rgb(0, 0, 0);\n"
        "    background-color: rgb(255, 255, 0);\n"
        "}\n"
        "")
        self.multiBtn.setObjectName("multiBtn")
        self.fourBtn = QtWidgets.QPushButton(self.centralwidget)
        self.fourBtn.setGeometry(QtCore.QRect(10, 290, 91, 91))
        self.fourBtn.setStyleSheet("QPushButton{\n"
        "font: 75 26pt \"MS Shell Dlg 2\";\n"
        "color: rgb(255, 255, 255);\n"
        "background-color: rgb(0,0,0);\n"
        "border:2px solid;\n"
        "border-color: rgb(0, 255, 0);\n"
        "border-radius:20px;\n"
        "}\n"
        "QPushButton:hover{\n"
        "    color: rgb(0, 0, 0);\n"
        "    \n"
        "    background-color: rgb(0, 255, 0);\n"
        "}\n"
        "")
        self.fourBtn.setObjectName("fourBtn")
        self.fiveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.fiveBtn.setGeometry(QtCore.QRect(110, 290, 91, 91))
        self.fiveBtn.setStyleSheet("QPushButton{\n"
        "font: 75 26pt \"MS Shell Dlg 2\";\n"
        "color: rgb(255, 255, 255);\n"
        "background-color: rgb(0,0,0);\n"
        "border:2px solid;\n"
        "border-color: rgb(0, 255, 0);\n"
        "border-radius:20px;\n"
        "}\n"
        "QPushButton:hover{\n"
        "    color: rgb(0, 0, 0);\n"
        "    \n"
        "    background-color: rgb(0, 255, 0);\n"
        "}\n"
        "")
        self.fiveBtn.setObjectName("fiveBtn")
        self.subBtn = QtWidgets.QPushButton(self.centralwidget)
        self.subBtn.setGeometry(QtCore.QRect(310, 290, 91, 91))
        self.subBtn.setStyleSheet("QPushButton{\n"
        "font: 75 26pt \"MS Shell Dlg 2\";\n"
        "color: rgb(255, 255, 255);\n"
        "background-color: rgb(0,0,0);\n"
        "border:2px solid;\n"
        "border-color: rgb(255, 255, 0);\n"
        "border-radius:20px;\n"
        "}\n"
        "QPushButton:hover{\n"
        "    color: rgb(0, 0, 0);\n"
        "    background-color: rgb(255, 255, 0);\n"
        "}\n"
        "")
        self.subBtn.setObjectName("subBtn")
        self.sixBtn = QtWidgets.QPushButton(self.centralwidget)
        self.sixBtn.setGeometry(QtCore.QRect(210, 290, 91, 91))
        self.sixBtn.setStyleSheet("QPushButton{\n"
        "font: 75 26pt \"MS Shell Dlg 2\";\n"
        "color: rgb(255, 255, 255);\n"
        "background-color: rgb(0,0,0);\n"
        "border:2px solid;\n"
        "border-color: rgb(0, 255, 0);\n"
        "border-radius:20px;\n"
        "}\n"
        "QPushButton:hover{\n"
        "    color: rgb(0, 0, 0);\n"
        "    \n"
        "    background-color: rgb(0, 255, 0);\n"
        "}\n"
        "")
        self.sixBtn.setObjectName("sixBtn")
        self.oneBtn = QtWidgets.QPushButton(self.centralwidget)
        self.oneBtn.setGeometry(QtCore.QRect(10, 390, 91, 91))
        self.oneBtn.setStyleSheet("QPushButton{\n"
        "font: 75 26pt \"MS Shell Dlg 2\";\n"
        "color: rgb(255, 255, 255);\n"
        "background-color: rgb(0,0,0);\n"
        "border:2px solid;\n"
        "border-color: rgb(0, 255, 0);\n"
        "border-radius:20px;\n"
        "}\n"
        "QPushButton:hover{\n"
        "    color: rgb(0, 0, 0);\n"
        "    \n"
        "    background-color: rgb(0, 255, 0);\n"
        "}\n"
        "")
        self.oneBtn.setObjectName("oneBtn")
        self.twoBtn = QtWidgets.QPushButton(self.centralwidget)
        self.twoBtn.setGeometry(QtCore.QRect(110, 390, 91, 91))
        self.twoBtn.setStyleSheet("QPushButton{\n"
        "font: 75 26pt \"MS Shell Dlg 2\";\n"
        "color: rgb(255, 255, 255);\n"
        "background-color: rgb(0,0,0);\n"
        "border:2px solid;\n"
        "border-color: rgb(0, 255, 0);\n"
        "border-radius:20px;\n"
        "}\n"
        "QPushButton:hover{\n"
        "    color: rgb(0, 0, 0);\n"
        "    \n"
        "    background-color: rgb(0, 255, 0);\n"
        "}\n"
        "")
        self.twoBtn.setObjectName("twoBtn")
        self.addBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addBtn.setGeometry(QtCore.QRect(310, 390, 91, 91))
        self.addBtn.setStyleSheet("QPushButton{\n"
        "font: 75 26pt \"MS Shell Dlg 2\";\n"
        "color: rgb(255, 255, 255);\n"
        "background-color: rgb(0,0,0);\n"
        "border:2px solid;\n"
        "border-color: rgb(255, 255, 0);\n"
        "border-radius:20px;\n"
        "}\n"
        "QPushButton:hover{\n"
        "    color: rgb(0, 0, 0);\n"
        "    background-color: rgb(255, 255, 0);\n"
        "}\n"
        "\n"
        "")
        self.addBtn.setObjectName("addBtn")
        self.threeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.threeBtn.setGeometry(QtCore.QRect(210, 390, 91, 91))
        self.threeBtn.setStyleSheet("QPushButton{\n"
        "font: 75 26pt \"MS Shell Dlg 2\";\n"
        "color: rgb(255, 255, 255);\n"
        "background-color: rgb(0,0,0);\n"
        "border:2px solid;\n"
        "border-color: rgb(0, 255, 0);\n"
        "border-radius:20px;\n"
        "}\n"
        "QPushButton:hover{\n"
        "    color: rgb(0, 0, 0);\n"
        "    \n"
        "    background-color: rgb(0, 255, 0);\n"
        "}\n"
        "")
        self.threeBtn.setObjectName("threeBtn")
        self.zeroBtn = QtWidgets.QPushButton(self.centralwidget)
        self.zeroBtn.setGeometry(QtCore.QRect(10, 490, 191, 91))
        self.zeroBtn.setStyleSheet("QPushButton{\n"
        "font: 75 26pt \"MS Shell Dlg 2\";\n"
        "color: rgb(255, 255, 255);\n"
        "background-color: rgb(0,0,0);\n"
        "border:2px solid;\n"
        "border-color: rgb(0, 255, 0);\n"
        "border-radius:20px;\n"
        "}\n"
        "QPushButton:hover{\n"
        "    color: rgb(0, 0, 0);\n"
        "    \n"
        "    background-color: rgb(0, 255, 0);\n"
        "}\n"
        "")
        self.zeroBtn.setObjectName("zeroBtn")
        self.equalToBtn = QtWidgets.QPushButton(self.centralwidget)
        self.equalToBtn.setGeometry(QtCore.QRect(310, 490, 91, 91))
        self.equalToBtn.setStyleSheet("QPushButton{\n"
        "font: 75 26pt \"MS Shell Dlg 2\";\n"
        "color: rgb(255, 255, 255);\n"
        "background-color: rgb(0,0,0);\n"
        "border:2px solid;\n"
        "border-color: rgb(255, 255, 0);\n"
        "border-radius:20px;\n"
        "}\n"
        "QPushButton:hover{\n"
        "    color: rgb(0, 0, 0);\n"
        "    \n"
        "    background-color: rgb(255, 255, 0);\n"
        "}\n"
        "")
        self.equalToBtn.setObjectName("equalToBtn")
        self.dotBtn = QtWidgets.QPushButton(self.centralwidget)
        self.dotBtn.setGeometry(QtCore.QRect(210, 490, 91, 91))
        self.dotBtn.setStyleSheet("QPushButton{\n"
        "font: 75 26pt \"MS Shell Dlg 2\";\n"
        "color: rgb(255, 255, 255);\n"
        "background-color: rgb(0,0,0);\n"
        "border:2px solid;\n"
        "border-color: rgb(0, 255, 0);\n"
        "border-radius:20px;\n"
        "}\n"
        "QPushButton:hover{\n"
        "    color: rgb(0, 0, 0);\n"
        "    \n"
        "    background-color: rgb(0, 255, 0);\n"
        "}\n"
        "")
        self.dotBtn.setObjectName("dotBtn")
        self.inbox = QtWidgets.QLabel(self.centralwidget)
        self.inbox.setGeometry(QtCore.QRect(10, 10, 391, 71))
        self.inbox.setStyleSheet("background-color: rgb(0, 0, 0);\n"
        "color: rgb(255, 255, 255);\n"
        "font:75 26pt;\n"
        "border:2px solid;\n"
        "border-color: rgb(255, 255, 255);\n"
        "border-radius: 20px;")
        self.inbox.setText("")
        self.inbox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.inbox.setObjectName("inbox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.acBtn.setText(_translate("MainWindow", "C"))
        self.acBtn.setShortcut(_translate("MainWindow", "Esc"))
        self.nineBtn.setText(_translate("MainWindow", "9"))
        self.nineBtn.setShortcut(_translate("MainWindow", "9"))
        self.eightBtn.setText(_translate("MainWindow", "8"))
        self.eightBtn.setShortcut(_translate("MainWindow", "8"))
        self.sevenBtn.setText(_translate("MainWindow", "7"))
        self.sevenBtn.setShortcut(_translate("MainWindow", "7"))
        self.delBtn.setText(_translate("MainWindow", "DEL"))
        self.delBtn.setShortcut(_translate("MainWindow", "Del"))
        self.divBtn.setText(_translate("MainWindow", "÷"))
        self.divBtn.setShortcut(_translate("MainWindow", "/"))
        self.multiBtn.setText(_translate("MainWindow", "×"))
        self.multiBtn.setShortcut(_translate("MainWindow", "*"))
        self.fourBtn.setText(_translate("MainWindow", "4"))
        self.fourBtn.setShortcut(_translate("MainWindow", "4"))
        self.fiveBtn.setText(_translate("MainWindow", "5"))
        self.fiveBtn.setShortcut(_translate("MainWindow", "5"))
        self.subBtn.setText(_translate("MainWindow", "-"))
        self.subBtn.setShortcut(_translate("MainWindow", "-"))
        self.sixBtn.setText(_translate("MainWindow", "6"))
        self.sixBtn.setShortcut(_translate("MainWindow", "6"))
        self.oneBtn.setText(_translate("MainWindow", "1"))
        self.oneBtn.setShortcut(_translate("MainWindow", "1"))
        self.twoBtn.setText(_translate("MainWindow", "2"))
        self.twoBtn.setShortcut(_translate("MainWindow", "2"))
        self.addBtn.setText(_translate("MainWindow", "+"))
        self.addBtn.setShortcut(_translate("MainWindow", "+"))
        self.threeBtn.setText(_translate("MainWindow", "3"))
        self.threeBtn.setShortcut(_translate("MainWindow", "3"))
        self.zeroBtn.setText(_translate("MainWindow", "0"))
        self.zeroBtn.setShortcut(_translate("MainWindow", "0"))
        self.equalToBtn.setText(_translate("MainWindow", "="))
        self.equalToBtn.setShortcut(_translate("MainWindow", "="))
        self.equalToBtn.setShortcut(_translate("MainWindow", "Return"))
        self.dotBtn.setText(_translate("MainWindow", "."))
        self.dotBtn.setShortcut(_translate("MainWindow", "."))
        
        self.oneBtn.clicked.connect(self.Num1)
        self.twoBtn.clicked.connect(self.Num2)
        self.threeBtn.clicked.connect(self.Num3)
        self.fourBtn.clicked.connect(self.Num4)
        self.fiveBtn.clicked.connect(self.Num5)
        self.sixBtn.clicked.connect(self.Num6)
        self.sevenBtn.clicked.connect(self.Num7)
        self.eightBtn.clicked.connect(self.Num8)
        self.nineBtn.clicked.connect(self.Num9)
        self.zeroBtn.clicked.connect(self.Num0)
        self.dotBtn.clicked.connect(self.dot)
        self.acBtn.clicked.connect(self.clear)
        self.delBtn.clicked.connect(self.delete)
        self.addBtn.clicked.connect(self.add)
        self.subBtn.clicked.connect(self.sub)
        self.multiBtn.clicked.connect(self.multi)
        self.divBtn.clicked.connect(self.div)
        self.equalToBtn.clicked.connect(self.equalTo)
        
    def Num1(self):
            text=self.inbox.text()
            self.inbox.setText(text+"1")
    def Num2(self):
            text=self.inbox.text()
            self.inbox.setText(text+"2")
    def Num3(self):
            text=self.inbox.text()
            self.inbox.setText(text+"3")
    def Num4(self):
            text=self.inbox.text()
            self.inbox.setText(text+"4")
    def Num5(self):
            text=self.inbox.text()
            self.inbox.setText(text+"5")
    def Num6(self):
            text=self.inbox.text()
            self.inbox.setText(text+"6")
    def Num7(self):
            text=self.inbox.text()
            self.inbox.setText(text+"7")
    def Num8(self):
            text=self.inbox.text()
            self.inbox.setText(text+"8")
    def Num9(self):
            text=self.inbox.text()
            self.inbox.setText(text+"9")
    def Num0(self):
            text=self.inbox.text()
            self.inbox.setText(text+"0")
    def dot(self):
            text=self.inbox.text()
            self.inbox.setText(text+".")
    def clear(self):
            self.inbox.setText("")
    def delete(self):
            text=self.inbox.text()
            self.inbox.setText(text[:len(text)-1])
    def add(self):
            text=self.inbox.text()
            self.inbox.setText(text+"+")
    def sub(self):
            text=self.inbox.text()
            self.inbox.setText(text+"-")
    def multi(self):
            text=self.inbox.text()
            self.inbox.setText(text+"*")
    def div(self):
            text=self.inbox.text()
            self.inbox.setText(text+"/")
    def equalTo(self):
            text=self.inbox.text()
            self.inbox.setText(str(eval(text)))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
